apiVersion: v1
metadata:
  name: kube-lego
  namespace: nginx-ingress
data:
  lego.email: {{ .Values.acmeEmail |  quote }}
  # configure letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
