# External service named "mariadb" that exposes the mariadb API and backup ports
apiVersion: v1
kind: Service
metadata:
  labels:
    app: extendedmind
    tier: backend
    project: backend
    group: org.extendedmind
  name: mariadb
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    name: mariadb
  selector:
    project: mariadb-galera
