# kubectl api-versions | grep rbac
## if yes -> RBAC is enabled
#
## in GKE: this might be needed
# gcloud config set container/use_client_certificate True
# export CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True
# gcloud container clusters get-credential
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: extmd-service
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: extmd-service
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: extmd-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extmd-service
subjects:
- kind: ServiceAccount
  name: extmd-service
  namespace: kube-system
