apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: extmd
  annotations:
    cert-manager.io/issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ext.md
    secretName: ext-md-tls
  rules:
  - host: ext.md
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 8008
