quayIoOrg: "extmd"
extmdBuildNumber: "${buildNumber}"

# Versions of docker images
backendDiscoveryVersion: "${extendedmind.backendDiscoveryVersion}"
backendRestoreVersion: "${extendedmind.backendRestoreVersion}"
backendVersion: "${extendedmind.backendVersion}"
backendBackupVersion: "${extendedmind.backendBackupVersion}"
syncFolderVersion: "${extendedmind.syncFolderVersion}"
# The next two use the same value on purpose
siteStaticVersion: "${extmd.siteVersion}"
siteVersion: "${extmd.siteVersion}"
appVersion: "${extmd.appVersion}"
etcInitVersion: "${extmd.etcInitVersion}"
piwikInitVersion: "${extmd.piwikInitVersion}"
fiakVersion: "${fiak.version}"

# App settings
extraAppJobSuffix: "-${buildNumber}"

# Site settings
siteHostName: "extmd-site"
extraSiteStaticJobSuffix: "-${buildNumber}"

# Piwik settings
piwikSalt: ${extmd.piwikSalt}
piwikSecure: ${extmd.piwikSecure}
piwikUsername: "piwik"
piwikPassword: "${extmd.mariaDbPiwikPassword}"

# Fiak settings
fiakFrontendReplicas: ${extmd.fiakFrontendReplicas}

# Nginx passwords
analyticspass: "${extmd.analyticsPass}"
dashboardpass: "${extmd.dashboardPass}"
urlOrigin: "${extendedmind.urlOrigin}"

# ACME settings
acmeEmail: "${extmd.acmeEmail}"
