## nginx ingress configuration
## Ref: https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/values.yaml
controller:
  kind: DaemonSet
  daemonset:
    useHostPort: true
  stats:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
