quayIoOrg: "extmd"
extmdBuildNumber: "${buildNumber}"

# Versions of docker images
backendDiscoveryVersion: "${extendedmind.backendDiscoveryVersion}"
backendRestoreVersion: "${extendedmind.backendRestoreVersion}"
backendVersion: "${extendedmind.backendVersion}"
backendBackupVersion: "${extendedmind.backendBackupVersion}"
syncFolderVersion: "${extendedmind.syncFolderVersion}"
# The next two use the same value on purpose
siteStaticVersion: "${extmd.siteVersion}"
siteVersion: "${extmd.siteVersion}"
appVersion: "${extmd.appVersion}"
etcInitVersion: "${extmd.etcInitVersion}"


# Resource Usage
backendBackupResources:
  limits:
    memory: 100Mi
    cpu: 50m
  requests:
    memory: 100Mi
    cpu: 50m
backendTickResources:
  limits:
    memory: 10Mi
    cpu: 10m
  requests:
    memory: 10Mi
    cpu: 10m
backendResources:
  limits:
    memory: 700Mi
    cpu: 200m
  requests:
    memory: 700Mi
    cpu: 200m
frontendSiteResources:
  limits:
    memory: 100Mi
    cpu: 100m
  requests:
    memory: 100Mi
    cpu: 100m
frontendSyncResources:
  limits:
    memory: 10Mi
    cpu: 10m
  requests:
    memory: 10Mi
    cpu: 10m
frontendNginxResources:
  limits:
    memory: 100Mi
    cpu: 50m
  requests:
    memory: 100Mi
    cpu: 50m

# App settings
extraAppJobSuffix: "-${buildNumber}"

# Site settings
siteHostName: "extmd-site"
extraSiteStaticJobSuffix: "-${buildNumber}"

# Fiak settings
fiakFrontendReplicas: ${extmd.fiakFrontendReplicas}
fiakNfsSyncSource: ${extmd.fiakNfsSyncSource}

# Nginx passwords
analyticspass: "${extmd.analyticsPass}"
dashboardpass: "${extmd.dashboardPass}"
urlOrigin: "${extendedmind.urlOrigin}"

# ACME settings
acmeServer: "${extmd.acmeServer}"
acmeEmail: "${extmd.acmeEmail}"
