## nginx ingress configuration
## Ref: https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/values.yaml
controller:
  kind: DaemonSet
  daemonset:
    useHostPort: true
  metrics:
    enabled: false
  resources:
    limits:
      cpu: 50m
      memory: 90Mi
    requests:
      cpu: 50m
      memory: 90Mi
defaultBackend:
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi
