apiVersion: v1
kind: Secret
metadata:
  name: piwik-secrets
  labels:
    project: helm
    group: md.ext
type: Opaque
data:
  piwikPassword: {{ b64enc .Values.piwikPassword | quote }}
  analyticspass: {{ b64enc .Values.analyticspass | quote }}
