apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: piwik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: extendedmind
        tier: frontend
        role: analytics
        project: helm
        group: md.ext
    spec:
      initContainers:
      - name: nginx-etc-init
        image: quay.io/extmd/piwik-init:{{ .Values.piwikInitVersion }}
        volumeMounts:
        - name: enableddir
          mountPath: "/etc/nginx/sites-enabled"
        - name: piwiktemplatesdir
          mountPath: "/etc/piwik/templates"
      containers:
      - name: piwik
        image: quay.io/extendedmind/piwik:piwik-3.0.3
        env:
          - name: EXTENDEDMIND_DB_PIWIKUSERNAME
            value: {{ .Values.piwikUsername | quote }}
          - name: EXTENDEDMIND_DB_PIWIKPASSWORD
            valueFrom:
              secretKeyRef:
                name: "piwik-secrets"
                key: piwikPassword
          - name: EXTENDEDMIND_DB_PIWIKSALT
            value: {{ .Values.piwikSalt | quote }}
          - name: EXTENDEDMIND_DB_PIWIKSECURE
            value: {{ .Values.piwikSecure | quote }}
          - name: EXTENDEDMIND_HOST
            value: {{ .Values.urlOrigin | quote }}
        ports:
        - name: piwik
          containerPort: 9000
        volumeMounts:
        - name: piwiktemplatesdir
          mountPath: "/etc/piwik/templates"
        - name: piwikdir
          mountPath: "/var/www/html"
      - name: nginx
        image: quay.io/extendedmind/nginx:nginx-1.13.0-1
        ports:
        - name: piwik
          containerPort: 8006
        volumeMounts:
        - name: piwikdir
          mountPath: "/var/www/html"
          readOnly: true
        - name: enableddir
          mountPath: "/etc/nginx/sites-enabled"
          readOnly: true
        - name: secretdir
          mountPath: /etc/nginx/secret
          readOnly: true
      volumes:
      - name: enableddir
        emptyDir: {}
      - name: piwiktemplatesdir
        emptyDir: {}
      - name: piwikdir
        emptyDir: {}
      - name: secretdir
        secret:
          secretName: "piwik-secrets"
