apiVersion: v1
kind: Secret
metadata:
  name: nginx-secrets
  labels:
    project: backend
    version: "${project.version}"
    group: org.extendedmind
type: Opaque
data:
  analyticspass: {{ b64enc .Values.analyticspass | quote }}
  dashboardpass: {{ b64enc .Values.dashboardpass | quote }}
