apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginxReplicas }}
  template:
    metadata:
      labels:
        app: extendedmind
        tier: frontend
        role: proxy
        project: frontend-site
        group: org.extendedmind.frontend
    spec:
      initContainers:
      - name: nginx-etc-init
        image: quay.io/{{ .Values.quayIoOrg }}/etc-init:{{ .Values.etcInitVersion }}
        volumeMounts:
        - name: enableddir
          mountPath: "/etc/nginx/sites-enabled"
      containers:
      - name: nginx
        image: quay.io/extendedmind/nginx:nginx-1.13.0-1
        ports:
        - name: dashboard
          containerPort: 8007
        - name: site
          containerPort: 8008
        - name: fiak
          containerPort: 8009
        volumeMounts:
        - name: enableddir
          mountPath: "/etc/nginx/sites-enabled"
          readOnly: true
        - name: publicdir
          mountPath: /app/site-public
          readOnly: true
          subPath: extendedmind
        - name: publicdir
          mountPath: /app/fiak-site-public
          readOnly: true
          subPath: fiak
        - name: secretdir
          mountPath: /etc/nginx/secret
          readOnly: true
      volumes:
      - name: enableddir
        emptyDir: {}
      - name: publicdir
        persistentVolumeClaim:
          claimName: shared
      - name: secretdir
        secret:
          secretName: "nginx-secrets"
